// <auto-generated />
using CleanArchitecture.StaticEntity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.StaticEntity.Migrations
{
    [DbContext(typeof(PersistenceContext))]
    partial class PersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("CleanArchitecture.StaticEntity.Entities.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Gender = 1,
                            Name = "Hugh Mann"
                        },
                        new
                        {
                            ID = 2,
                            Gender = 2,
                            Name = "Amanda Huggen-Kiss"
                        },
                        new
                        {
                            ID = 3,
                            Gender = 3,
                            Name = "GennY McStable"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
